project:
  name: vivipi

device:
  board: pico2w
  micropython_port: /dev/ttyACM0
  micropython:
    version: 1.25.0
    download_page: https://micropython.org/download/RPI_PICO2_W/
  buttons:
    a: GP14
    b: GP15
  display:
    controller: sh1107
    width_px: 128
    height_px: 64
    interface: spi
    spi_mode: 3
    mode: standard
    columns: 2
    column_separator: " "
    brightness: compact
    page_interval: 15s
    font:
      width_px: 16
      height_px: 16
    pins:
      vcc: VSYS
      gnd: GND
      din: GP11
      clk: GP10
      cs: GP9
      dc: GP8
      rst: GP12

wifi:
  ssid: ${VIVIPI_WIFI_SSID}
  password: ${VIVIPI_WIFI_PASSWORD}

service:
  base_url: ${VIVIPI_SERVICE_BASE_URL}
  default_prefix: adb

checks_config: checks.yaml
